# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('genre', models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer')], max_length=50)),
                ('age', models.IntegerField()),
                ('country', models.CharField(max_length=50)),
                ('oscars', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('genre', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('country', models.CharField(max_length=50)),
                ('oscars', models.IntegerField()),
                ('cast', models.ManyToManyField(to='movies.Actor')),
            ],
        ),
    ]
