# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='genre',
            new_name='sex',
        ),
        migrations.AlterField(
            model_name='movie',
            name='cast',
            field=models.ManyToManyField(related_name='actors', to='movies.Actor'),
        ),
    ]
